/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Set of available settings for tender
 */
export interface TenderConfig {
  /**
   * List of settings for tenders
   */
  configs: Config[];
  [k: string]: unknown;
}
/**
 * Set of available settings for tender
 */
export interface Config {
  /**
   * Unique id to identify tender
   */
  id: string;
  /**
   * Indicates whether reconciliation of amount is required
   */
  doReconcileAmount?: null | boolean;
  /**
   * Indicates whether reconciliation of quantity is required
   */
  doReconcileQuantity?: null | boolean;
  /**
   * Indicates the cash is handled by a cash changer
   */
  isCashChanger?: null | boolean;
  /**
   * Maximum allowed amount in cash drawer, if exceeded, a warning will be triggered.
   */
  maxAllowedAmount?: null | number;
  /**
   * Minimum allowed amount in cash drawer, if below, a warning will be triggered.
   */
  minAllowedAmount?: null | number;
  /**
   * The maximum allowed deviation for quantity, for a single reconciliation.
   */
  maxAllowedDeviationQuantity?: null | number;
  /**
   * The maximum allowed deviation for amount, for a single reconciliation.
   */
  maxAllowedDeviationAmount?: null | number;
  /**
   * The maximum allowed deviation for quantity, for the business unit (includes all reconciliations)
   */
  maxAllowedStoreDeviationQuantity?: null | number;
  /**
   * The maximum allowed deviation for amount, for the business unit (includes all reconciliations).
   */
  maxAllowedStoreDeviationAmount?: null | number;
  /**
   * The value that will be used by default for the initial balance
   */
  defaultInitialBalance?: null | number;
  [k: string]: unknown;
}
