repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: fix-byte-order-marker
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
        args: [ --whitespaces-count=2 ]
-   repo: https://github.com/extenda/pre-commit-hooks.git
    rev: v0.9.0
    hooks:
    -   id: google-java-formatter
