/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of tenders with settings
 */
export type TenderConfigs = TenderConfig[];

/**
 * Tender with necessary settings
 */
export interface TenderConfig {
  /**
   * Unique id to identify tender
   */
  id: string;
  config: Config;
  [k: string]: unknown;
}
/**
 * Set of available settings for tender
 */
export interface Config {
  /**
   * The maximum allowed deviation for amount, for a single reconciliation.
   */
  maxAllowedDeviationAmount?: null | number;
  /**
   * Minimum amount when doing bank deposits, i.e. transfers from the repository to the bank
   */
  minAmountBankDeposit?: null | number;
  /**
   * Maximum allowed amount in safe, if exceeded, a warning will be triggered.
   */
  maxAllowedAmountInSafe?: null | number;
  /**
   * Minimum allowed amount in safe, if below, a warning will be triggered.
   */
  minAllowedAmountInSafe?: null | number;
  [k: string]: unknown;
}
