/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Reason Codes Schema
 */
export interface ReasonCodes {
  /**
   * List of available reason codes per tenant
   *
   * @minItems 1
   */
  reasonCodes: [ReasonCode, ...ReasonCode[]];
  [k: string]: unknown;
}
export interface ReasonCode {
  /**
   * The unique identifier
   */
  id: string;
  /**
   * The name of the reason code
   */
  name: string;
  /**
   * The description of the reason code
   */
  description?: string;
  /**
   * The status of the reason code
   */
  status: "Activated" | "Deactivated";
  /**
   * A flag that indicates whether manual entry is required, i.s. not allowed to scan
   */
  isManualEntryRequired?: boolean;
  /**
   * A flag that indicates whether a reference number is required
   */
  isReferenceNumberRequired?: boolean;
  /**
   * A flag that indicates whether a comment is required
   */
  isCommentRequired?: boolean;
  /**
   * A flag that indicates whether the quantity by default is negative
   */
  isNegativeQuantityByDefault?: boolean;
  /**
   * The minimum amount allowed to be entered
   */
  minimumAmount?: number;
  /**
   * The maximum amount allowed to be entered
   */
  maximumAmount?: number;
  /**
   * Group IDs assigned to a specific reason code. ID must be a valid ID from predefined reason code groups list
   */
  groups?: (
    | "Refund"
    | "OverwritePrice"
    | "MarkDownOrder"
    | "MarkDownPrice"
    | "Disbursement"
    | "FundsReceipt"
    | "NoSale"
    | "CancelOrder"
    | "ItemComment"
    | "TransactionComment"
    | "Complaint"
  )[];
  [k: string]: unknown;
}
