/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of currencies
 */
export type Currencies = Currency[];

/**
 * The currency with configuration
 */
export interface Currency {
  /**
   * Unique id to currency using ISO4217 format
   */
  id: string;
  config: Config;
  [k: string]: unknown;
}
/**
 * Set of available settings for currency
 */
export interface Config {
  /**
   * Indicates if currency is used as default
   */
  isDefaultCurrency: boolean;
  [k: string]: unknown;
}
