on:
  pull_request:
  push:
    # paths:
    #   - customer-config/**
    # branches: master

jobs:
  get_files:
    name: run_on_pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.4
        with:
          since_last_remote_commit: 'true'

      - name: Create wokrking directory
        run: |
          mkdir diff_files

      - name: get_modified_files
        id: diff
        working-directory: './diff_files'
        run: |
          git config diff.renameLimit 99000
          git fetch origin $GITHUB_BASE_REF --depth=1
          touch files.txt
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file >> files.txt
          done
          cat files.txt | split -l 100 -a 8
          rm files.txt
          export filename_string=""
          for i in `ls`; do export filename_string=$filename_string"file!"$i; done
          echo $filename_string
