name: Action
on:
  pull_request:
  push:
    paths:
      - '.github/actions/sync-action/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/actions/sync-action

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM install
        run: npm ci

      - name: Build and Lint javascript
        run: npm run lint

      - name: Unit tests
        run: npm test
